name = "UnivariateApprox"
uuid = "549aa1d2-f639-4cc7-b8e4-a7f233081321"
authors = ["Daniel Sharp <dannys4@mit.edu> and contributors"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
FFTW = "1.8.1"
LinearAlgebra = ">=1.7"
MuladdMacro = "0.2.4"
Serialization = ">=1.7"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
